name: Staging Branch

on:
  push:
    branches:
      - sprint0
      - sprint1
      - sprint2
      - sprint3
      - sprint4

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "Deploy the web dyno"
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: swj-capstone-staging
          heroku_email: "hobang1@udayton.edu"
          justlogin: true

      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app swj-capstone-staging

      - name: "Releases the container"
        run: heroku container:release web --app swj-capstone-staging
